# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Mammad Mirza
description: "Hello, Iâ€™m Mammad. I am an AI/ML Scientist with a PhD in Engineering and with expertise in applied ML, physics-based modeling, and optimization for energy systems. I use Python and frameworks such as LangChain, Langflow, Azure OpenAI, Hugging Face, as well as OpenAI APIs to build RAG-enabled copilots, semantic search tools, and intelligent agents. Furthermore, I am proficient in prompt engineering, vector search, and agent orchestration, with a strong programming foundation. Passionate about ethical, transparent AI and the responsible advancement of ML in impactful domains, such as healthcare, computer vision, clean energy, CCUS, mineral extraction, and reservoir simulation. Feel free to explore my projects or connect with me using my Linkedin profile link below."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Project <span style="color:#f58506"> Portfolio </span>
location: "Calgary, AB"
resume_url: /docs/resume.docx
avatar_image: /img/profile_picture.JPG

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/mammad-mirza#" # Add your linkedln handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/









